version: '3.8'

services:
  app:
    build: .
    container_name: agricultural-ai-service
    restart: unless-stopped
    ports:
      - "5001:5000"
    volumes:
      - ./data:/app/data
      - ./weight:/app/weight
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    environment:
      - MPLCONFIGDIR=/app/data/matplotlib
      - YOLO_CONFIG_DIR=/app/data/yolo
      - FLASK_APP=app.py
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  redis_data: 