version: '3.8'

services:
  app:
    build: .
    container_name: agricultural-ai-service
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./weight:/app/weight
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    environment:
      - REDIS_URL=redis://redis:6379/0
      - FLASK_APP=app.py
      - FLASK_ENV=production
    depends_on:
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  redis:
    image: redis:7.2-alpine
    container_name: agricultural-ai-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_data: 