name: pytorch_310
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10.15
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - numpy=1.24.3
  - pip:
      - flask==3.1.0
      - flask-cors==3.0.10
      - flask-jwt-extended==4.7.1
      - flask-socketio==5.4.1
      - flask-sqlalchemy==3.1.1
      - torchvision==0.16.2
      - torchaudio==2.1.2
      - opencv-python==4.8.1.78
      - pandas==2.1.4
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - matplotlib==3.8.2
      - seaborn==0.13.0
      - celery==5.3.6
      - redis==5.0.1
      - sqlalchemy==2.0.23
      - streamlit==1.29.0
      - ultralytics==8.3.146
      - python-dotenv==1.0.0
      - gunicorn==21.2.0
      - waitress==3.0.0
      - onnx==1.15.0
      - onnxruntime==1.16.3
      - onnxruntime-gpu==1.16.3
      - psutil==5.9.8
      - python-multipart==0.0.9
      - Pillow==10.2.0
      - requests==2.31.0
      - tqdm==4.66.2
