disease_mapping = {
    "Tomato___Late_blight": "番茄晚疫病",
    "Tomato___healthy": "健康番茄",
    "Grape___healthy": "健康葡萄",
    "Orange___Haunglongbing_(Citrus_greening)": "橙黄龙病（柑橘黄化病）",
    "Soybean___healthy": "健康大豆",
    "Squash___Powdery_mildew": "南瓜白粉病",
    "Potato___healthy": "健康土豆",
    "Corn_(maize)__Northern_Leaf_Blight": "玉米北方叶枯病",
    "Tomato___Early_blight": "番茄早疫病",
    "Tomato___Septoria_leaf_spot": "番茄斑点病（Septoria）",
    "Corn(maize)__Cercospora_leaf_spot Gray_leaf_spot": "玉米灰叶斑病",
    "Strawberry___Leaf_scorch": "草莓叶焦病",
    "Peach___healthy": "健康桃子",
    "Apple___Apple_scab": "苹果疮痂病",
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": "番茄黄叶卷曲病毒病",
    "Tomato___Bacterial_spot": "番茄细菌性斑点病",
    "Apple___Black_rot": "苹果黑腐病",
    "Blueberry___healthy": "健康蓝莓",
    "Cherry(including_sour)__Powdery_mildew": "樱桃白粉病",
    "Peach___Bacterial_spot": "桃子细菌性斑点病",
    "Apple___Cedar_apple_rust": "苹果雪松锈病",
    "Tomato___Target_Spot": "番茄靶斑病",
    "Pepper,bell___healthy": "健康甜椒",
    "Grape___Leaf_blight(Isariopsis_Leaf_Spot)": "葡萄叶斑病（Isariopsis叶斑）",
    "Potato___Late_blight": "土豆晚疫病",
    "Tomato___Tomato_mosaic_virus": "番茄花叶病毒病",
    "Strawberry___healthy": "健康草莓",
    "Apple___healthy": "健康苹果",
    "Grape___Black_rot": "葡萄黑腐病",
    "Potato___Early_blight": "土豆早疫病",
    "Cherry(including_sour)__healthy": "健康樱桃（包括酸樱桃）",
    "Corn(maize)_Common_rust": "玉米常见锈病",
    "Grape___Esca(Black_Measles)": "葡萄Esca病（黑斑病）",
    "Raspberry___healthy": "健康覆盆子",
    "Tomato___Leaf_Mold": "番茄叶霉病",
    "Tomato___Spider_mites Two-spotted_spider_mite": "番茄蜘蛛螨（两点蜘蛛螨）",
    "Pepper,bell___Bacterial_spot": "甜椒细菌性斑点病",
    "Corn(maize)___healthy": "健康玉米",
}
