disease_mapping = {
    "Tomato___Late_blight": "番茄___晚疫病",
    "Tomato___healthy": "番茄___健康",
    "Grape___healthy": "葡萄___健康",
    "Orange___Haunglongbing_(Citrus_greening)": "橙子___黄龙病（柑橘黄化病）",
    "Soybean___healthy": "大豆___健康",
    "Squash___Powdery_mildew": "南瓜___白粉病",
    "Potato___healthy": "土豆___健康",
    "Corn_(maize)__Northern_Leaf_Blight": "玉米___北方叶枯病",
    "Tomato___Early_blight": "番茄___早疫病",
    "Tomato___Septoria_leaf_spot": "番茄___叶斑病（Septoria）",
    "Corn(maize)__Cercospora_leaf_spot Gray_leaf_spot": "玉米___叶斑病（灰叶斑病）",
    "Strawberry___Leaf_scorch": "草莓___叶焦病",
    "Peach___healthy": "桃子___健康",
    "Apple___Apple_scab": "苹果___苹果疮痂病",
    "Tomato___Tomato_Yellow_Leaf_Curl_Virus": "番茄___番茄黄叶病毒",
    "Tomato___Bacterial_spot": "番茄___细菌性斑点病",
    "Apple___Black_rot": "苹果___黑腐病",
    "Blueberry___healthy": "蓝莓___健康",
    "Cherry(including_sour)__Powdery_mildew": "樱桃（包括酸樱桃）___白粉病",
    "Peach___Bacterial_spot": "桃子___细菌性斑点病",
    "Apple___Cedar_apple_rust": "苹果___雪松苹果锈病",
    "Tomato___Target_Spot": "番茄___靶斑病",
    "Pepper,bell___healthy": "甜椒（甜椒）___健康",
    "Grape___Leaf_blight(Isariopsis_Leaf_Spot)": "葡萄___叶斑病（Isariopsis叶斑）",
    "Potato___Late_blight": "土豆___晚疫病",
    "Tomato___Tomato_mosaic_virus": "番茄___番茄花叶病毒",
    "Strawberry___healthy": "草莓___健康",
    "Apple___healthy": "苹果___健康",
    "Grape___Black_rot": "葡萄___黑腐病",
    "Potato___Early_blight": "土豆___早疫病",
    "Cherry(including_sour)__healthy": "樱桃（包括酸樱桃）___健康",
    "Corn(maize)_Common_rust": "玉米___常见锈病",
    "Grape___Esca(Black_Measles)": "葡萄___Esca病（黑斑病）",
    "Raspberry___healthy": "覆盆子___健康",
    "Tomato___Leaf_Mold": "番茄___叶霉病",
    "Tomato___Spider_mites Two-spotted_spider_mite": "番茄___蜘蛛螨（两点蜘蛛螨）",
    "Pepper,bell___Bacterial_spot": "甜椒（甜椒）___细菌性斑点病",
    "Corn(maize)___healthy": "玉米___健康",
}
